-- =============================================================================
-- Phase 3 Step 6a: Chat binding tables
-- =============================================================================

alter table public.profiles
  add column if not exists telegram_user_id bigint unique,
  add column if not exists discord_user_id  text   unique,
  add column if not exists slack_user_id    text   unique;

-- 6-digit binding codes generated by the dashboard, consumed by chat bots.
create table if not exists public.binding_codes (
  code        text        primary key,
  user_id     uuid        not null references public.profiles(id) on delete cascade,
  platform    text        not null check (platform in ('telegram','discord','slack','whatsapp')),
  expires_at  timestamptz not null,
  used_at     timestamptz,
  created_at  timestamptz not null default now()
);
create index if not exists binding_codes_user_idx    on public.binding_codes (user_id)    where used_at is null;
create index if not exists binding_codes_expires_idx on public.binding_codes (expires_at) where used_at is null;

-- Short-lived tokens embedded in chat button callback_data / custom_id.
-- Service-role-only: worker writes, MCP reads. No browser access.
create table if not exists public.chat_callback_tokens (
  token         text        primary key,
  user_id       uuid        not null references public.profiles(id)  on delete cascade,
  pitch_id      uuid        not null references public.pitches(id)   on delete cascade,
  payload_hash  text        not null,
  action        text        not null check (action in ('approve','reject','edit')),
  expires_at    timestamptz not null,
  used_at       timestamptz,
  created_at    timestamptz not null default now()
);
create index if not exists chat_callback_tokens_pitch_idx on public.chat_callback_tokens (pitch_id);

alter table public.binding_codes        enable row level security;
alter table public.chat_callback_tokens enable row level security;

-- Users can read/insert their own binding codes from the dashboard.
create policy "binding_codes: read own"   on public.binding_codes
  for select to authenticated using (auth.uid() = user_id);
create policy "binding_codes: insert own" on public.binding_codes
  for insert to authenticated with check (auth.uid() = user_id);

-- chat_callback_tokens are service-role-only (no browser access by design).
create policy "chat_callback_tokens: service role insert" on public.chat_callback_tokens
  for insert to service_role with check (true);
create policy "chat_callback_tokens: service role select" on public.chat_callback_tokens
  for select to service_role using (true);
create policy "chat_callback_tokens: service role update" on public.chat_callback_tokens
  for update to service_role using (true);
